### ISSUE TITLE
"ol start" incorrect rendering

### ISSUE THREAD

**Issue by viT-1** [shower/shower#289]
Please check the drawing numbers for li elements.
Despite setting the attribute "start" li starts with the number 1.

**Comment by pepelsbey** [comment]
It’s still impossible to control native browser list numbering via CSS: `@counter-style` is supported [only in Firefox](https://developer.mozilla.org/en-US/docs/Web/CSS/@counter-style). That’s why I [auto-generate list numbers and bullets via counters](https://github.com/shower/ribbon/blob/master/styles/slide/content/lists.scss#L35-L46):

```css
ul > li::before {
	padding-right: 0.5em;
	content: '•';
	}
ul > li:lang(ru)::before {
	content: '—';
	}
ol > li::before {
	counter-increment: list;
	content: counter(list)'.';
	}
```

AFAIK, there’s no way to pass `start` attribute in such numbering. Correct me if I’m wrong.

@kizu, any weird hacks in your sleeve to support `start` in counters?

**Comment by pepelsbey** [comment]
I could probably add support for `value` attribute, [see demo](https://jsbin.com/mibuno/edit?html,css,output).

```html
<ol>
    <li value="4">first item</li>
    <li value="5">second item</li>
    <li value="6">third item</li>
</ol>
```

And

```css
li[value]::before {
    content: attr(value)'. ';
    }
```
