### ISSUE TITLE
Printing PDFs

### ISSUE THREAD

**Issue by rauschma** [shower/shower#294]
Printing the current slides via Chrome: [shower-chrome.pdf](https://github.com/shower/shower/files/1140459/shower-chrome.pdf)

Safari has similar problems. But they can be fixed by adding this CSS to `screen-16x10.css` (alas, this doesn’t fix Chrome’s problems):

```css
@media print {
    section {
        page-break-before: always;
        page-break-after: always;
    }
}
```

Result: [shower-safari-modified.pdf](https://github.com/shower/shower/files/1140461/shower-safari-modified.pdf)

Tables are still a bit off, but everything else looks the way I’d want.

Given several experiments with printing web pages (some of them included SVG graphics), it seems that Safari is better at printing than Chrome, at the moment.
