### ISSUE TITLE
Consider removing reset for <q> element

### ISSUE THREAD

**Issue by shvaikalesh** [shower/shower#307]
There are a lot of quotation marks ([wiki: summary table](https://en.wikipedia.org/wiki/Quotation_mark#Summary_table)) for different languages. `<q>` element abstracts them away, both primary and secondary quotation marks. That is the main reason I put `lang` on `<html>`: to control quotes.

Shower [resets](https://github.com/shower/ribbon/blob/4a45b78f4fe2136ae06329e90d1349f78bd00f6b/styles/_reset.scss#L48-L55) quotes for `<q>` element, while encourages usage of other semantic elements, like `<code>` or `<mark>`. What is the reasoning behind this?

<details>
<summary>My current workaround</summary>

```css
q { quotes: initial }
q::before { content: open-quote }
q::after { content: close-quote }
```
</details>
