### ISSUE TITLE
Change Next behaviour to match slides

### ISSUE THREAD

**Issue by pepelsbey** [shower/shower#338]
What’s currently happening when we move through slides:

```html
<section class="slide visited">
<section class="slide visited">
<section class="slide active"> ← the current slide
<section class="slide">
```

In case of the Next plugin it looks different:

```html
<li class="next active">
<li class="next active">
<li class="next active"> ← the current step
<li class="next">
```

There’s no truly active item (all of them are active), there’s no visited steps. Even with the same class names the principle is quite different. So I suggest we apply the same behavior to the Next plugin:

```html
<li class="next visited">
<li class="next visited">
<li class="next active"> ← the current step
<li class="next">
```

By default `.next` is invisible and `.active` triggers visibility:

```css
.shower.full .next {
    visibility: hidden;
}

.shower.full .next.active {
    visibility: visible;
}
```

In proposed case it would be something like:

```css
.shower.full .next {
    visibility: hidden;
}

.shower.full .next.active,
.shower.full .next.visited {
    visibility: visible;
}
```

It shouldn’t break anything since no one is usually customizing `.next` classed for their own needs. But it will make such customization possible for, let’s say, a gallery with a current element or something similar.

What do you think? @shvaikalesh @nikolay-govorov @avdeev
