### ISSUE TITLE
Create thumbs mode

### ISSUE THREAD

**Issue by pepelsbey** [shower/shower#52]
There's `<body class="list">` mode with 512x320 thumbnails. It's good for reading and browsing through the slides. But it would be great to have “thumbnails” mode only for browsing when you need to pick the right slide quickly. So it's the question of additional class name to the body (because it's just a minor change)

``` html
<body class="list thumbs">
```

and small changes in Ribbon theme:

``` css
.list.thumbs .slide > DIV {
    width:256px;
    height:160px;
    }
.list.thumbs .slide SECTION {
    transform:scale(0.25);
    }
```

There will be also reading-browsing mode switcher. But I wonder: how should we keep this mode while entering `?full` mode? For example, we can pass `?list` and `?thumb` parameters into URL just like with `?full`.

Discuss?
