### ISSUE TITLE
Implement support for slide transitions

### ISSUE THREAD

**Issue by pepelsbey** [shower/shower#59]
Something like that: http://jsfiddle.net/pepelsbey/W7DsB/

Basic principle here is: all previous slides to the current have additional class name `passed`

I think it wouldn't be a problem in current architecture.

**Comment by NeomMob** [comment]
Hi, Do you have any example of thme using transitions, just to understand how to add thme in a custm theme. Thanks !

**Comment by pepelsbey** [comment]
@NeomMob, you can just use CSS to implement transitions, see styles in [slide-full.scss](https://github.com/shower/ribbon/blob/master/styles/slide/slide-full.scss), available both in Ribbon and Material themes.

```scss
.slide {

	position:absolute;
	top:0;
	left:0;
	margin-left:-150%;
	visibility:hidden;

	// Current

	&:target {
		margin:0;
		visibility:visible;
		}

	}
```
By default slide is hidden off-screen by `margin-left:-150%` and visually hidden by `visibility:hidden`, but once it’s active `:target` changes it to `0` and `visible`. You can use any effects or transitions you like.
